/* Lean StartApp — app catalogue.
   To add an app: copy one { ... } block, fill in the fields, done.
   group must be one of the ids in APP_GROUPS below.
   The homepage renders these automatically. */

const APP_GROUPS = [
  { id: "audio", title: "Sound & Audio", kicker: "Boost · tune · record" },
  { id: "tools", title: "Tools & Utilities", kicker: "Install · focus" },
  { id: "fun", title: "Fun & Extras", kicker: "Camera · puzzles" },
];

const APPS = [
  {
    name: "Volume+",
    fn: "Volume booster",
    group: "audio",
    rating: "4.6",
    icon: "https://play-lh.googleusercontent.com/7EcuOrOWhIFQ1lMjNBfDdhRoBDSvTd1Wu4up3YjOG0isZpYSvsjZm5v_IaypsPTAev6R=s128-rw",
    url: "https://play.google.com/store/apps/details?id=boostvolume.soundbooster.soundamplifier.loudspeaker.increasevolume.soundenhancer.volumebooster",
    desc: "Push audio past the system limit for music, video and calls — with minimal distortion.",
    featured: true,
  },
  {
    name: "EQ+",
    fn: "Equalizer",
    group: "audio",
    rating: "4.8",
    icon: "https://play-lh.googleusercontent.com/_k261Im3VC73vHOUfuFQnEWTPCtgMwYLAacJqvefE_r4dR9cmNRftTnGiBo_Yw1Png=s128-rw",
    url: "https://play.google.com/store/apps/details?id=eqplus.equalizer.bassbooster.volumeeq.musicequalizer.basseq",
    desc: "A 10-band equalizer with clean presets and custom sound profiles.",
    featured: true,
  },
  {
    name: "Bass+",
    fn: "Bass booster",
    group: "audio",
    rating: "4.7",
    icon: "https://play-lh.googleusercontent.com/soHVyBGzG4VgJ7WrFH9LJT77ZBn1ta8d3-OBr0hoEHGGmz-YQZ4B5bhZDUV6K-xyChVZ=s128-rw",
    url: "https://play.google.com/store/apps/details?id=subwoofer.bassbooster.bassboosterapp.bass.booster.pro",
    desc: "Deep, rich low-end enhancement with simple, direct controls.",
    featured: true,
  },
  {
    name: "Recorder+",
    fn: "Voice recorder",
    group: "audio",
    rating: "4.6",
    icon: "https://play-lh.googleusercontent.com/9YgngxXe9tpPl3QAJNU51ORHtArHOIBbYUcwZUz0TbT898R1x33oHYIkgkK54e3AQcs=s128-rw",
    url: "https://play.google.com/store/apps/details?id=voice.recorder.audiorecorder.voicememos.media.audioeditor.hiqualityrecordingapp.voicerecorder",
    desc: "High-quality voice recording with noise reduction and one-tap sharing.",
    featured: true,
  },
  {
    name: "Voice Changer",
    fn: "Voice effects",
    group: "audio",
    rating: "4.3",
    icon: "https://play-lh.googleusercontent.com/NX-Vz7d0_SVnY0s85mo6DYRs_hXu3Q3bS4ous8R3T-WtoXSLofqgkRruFNBxWhyRkag=s128-rw",
    url: "https://play.google.com/store/apps/details?id=voicechanger.voiceeffects.voiceeditor.accentchanger.voicewarp.changevoice",
    desc: "Turn your voice into any effect and share the result in seconds.",
    featured: false,
  },
  {
    name: "Disable Headphone",
    fn: "Speaker toggle",
    group: "audio",
    rating: "4.7",
    icon: "https://play-lh.googleusercontent.com/7-ZvLYC00FmJYFoOr8GGmY5mhCfV5zemRl7xw3S8VSs7SHBu7-Hf479lZGVFTAIjSbI=s128-rw",
    url: "https://play.google.com/store/apps/details?id=headphonemodeoff.headphonejackfix.disableheadphone.enablespeaker",
    desc: "Force speaker output when the headphone jack sticks or stays on.",
    featured: false,
  },
  {
    name: "Speaker Cleaner",
    fn: "Water eject",
    group: "audio",
    rating: "4.9",
    icon: "https://play-lh.googleusercontent.com/EZ9DycLOCFcfCea5Ja0Vigt3EzjpAPZLY1jObCGJZ41OmlK47Kt6zRoX8ItUwDupGg=s128-rw",
    url: "https://play.google.com/store/apps/details?id=speakercleaner.removewater.fixsound.speakerwatercleaner",
    desc: "Eject water and clear dust from speakers and earpieces.",
    featured: true,
  },
  {
    name: "SAI+",
    fn: "APK installer",
    group: "tools",
    rating: "4.7",
    icon: "https://play-lh.googleusercontent.com/JsJ1MUNC4c-DnPVEpLfAe-SvLG5ak2rSbPtv1zTHT1pIGP4oUg0GNYQkFuu7p-vgtfOPKn8EZTsql8iIdQqldg=s128-rw",
    url: "https://play.google.com/store/apps/details?id=sai.split.apks.xapk.installer.obb.aab.xapkinstaller.saiplus",
    desc: "Install split APK, XAPK & APKM files, and back up your apps. Ad-light.",
    featured: true,
  },
  {
    name: "Flip Clock",
    fn: "Study timer",
    group: "tools",
    rating: "4.8",
    icon: "https://play-lh.googleusercontent.com/xRsQXlHnuxUY43vpOzEdBi5OFTsv5Sx9YXGEHPBpRxj5soVfnQz_u10j-IBSfl_5I9s=s128-rw",
    url: "https://play.google.com/store/apps/details?id=flip.clock.pomodoro.studytimer.studyclock.desktopclock.fliqlo.flipclock",
    desc: "A flip-style desk clock with a study and Pomodoro timer.",
    featured: true,
  },
  {
    name: "Blast Solver",
    fn: "Puzzle helper",
    group: "fun",
    rating: "4.3",
    icon: "https://play-lh.googleusercontent.com/fG84gbkJ1mXFb-brEYwQhXohm4nkdIxpmDFhzFbdyWoQoUqVIS1HtPMbPrq_SQykktv8=s128-rw",
    url: "https://play.google.com/store/apps/details?id=blockpuzzlehelper.blockblashelper.blockpuzzlesolver.blockblastsolver.pro",
    desc: "Smart hints and solutions for block-blast style puzzles.",
    featured: false,
  },
  {
    name: "Time Warp Scan",
    fn: "Camera effect",
    group: "fun",
    rating: "3.9",
    icon: "https://play-lh.googleusercontent.com/kLGjazWJffXIJEJ1LjLEzfmybBE1zd9NxGctqCEonpmTbZIy79kRyKFdHpoceLnlBnE=s128-rw",
    url: "https://play.google.com/store/apps/details?id=timewarpscan.bluelinefilter.timewarpscaneffect.timewarpscanfilterapp.bluelinefiltertiktok",
    desc: "The blue-line time-warp scan effect for fun camera clips.",
    featured: false,
  },
];

const REVIEWS = [
  { stars: "★★★★★", text: "Best free volume booster, hands down. Simple layout, does exactly what it says, minimal distortion, and no invasive ads interrupting my music. Worth the space.", name: "Terren B", app: "Volume+ user", initial: "T" },
  { stars: "★★★★★", text: "It's 10-band instead of 5–7 and has great presets. Just a small banner at the bottom instead of full-length ads that interrupt your music. A great app.", name: "Sonya Pitchforth", app: "EQ+ user", initial: "S" },
  { stars: "★★★★☆", text: "Nice and excellent — works on my phone like a big speaker. Good sound quality since I used this app. Thanks to the maker, more power.", name: "Jose Nuguid", app: "Bass+ user", initial: "J" },
  { stars: "★★★★★", text: "I dropped my phone in water and the speakers crackled. I didn't think this would work, but it worked perfectly — speakers sound as clear as before. Great app!", name: "Srijan Utkarsh", app: "Speaker Cleaner user", initial: "S" },
];
